definitions:
  models.EmptyResponse:
    properties:
      message:
        type: string
    type: object
  models.GetMemberResponse:
    properties:
      item:
        $ref: '#/definitions/models.Member'
    type: object
  models.ListMembersResponse:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/models.Member'
        type: array
      page:
        type: integer
      pages:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  models.Member:
    properties:
      category:
        type: string
      email:
        type: string
      end_date:
        format: date
        type: string
      id:
        type: integer
      kpi:
        type: integer
      level:
        type: integer
      name:
        type: string
      positions:
        items:
          type: string
        type: array
      start_date:
        format: date
        type: string
      status:
        type: string
      total_effort:
        type: number
    type: object
  models.UpsertMemberRequest:
    properties:
      category:
        type: string
      email:
        type: string
      end_date:
        type: string
      id:
        type: integer
      kpi:
        type: integer
      level:
        type: integer
      name:
        type: string
      positions:
        items:
          type: string
        minItems: 1
        type: array
      start_date:
        type: string
      status:
        type: string
      total_effort:
        type: number
    required:
    - category
    - email
    - kpi
    - level
    - name
    - positions
    - status
    - total_effort
    type: object
host: localhost:4000
info:
  contact:
    email: ntduy.cs@gmail.com
    name: Duy Nguyen
  description: Project Management API Document
  title: Project Management API Document
  version: "1.0"
paths:
  /members:
    get:
      consumes:
      - application/json
      parameters:
      - default: 1
        description: Page
        in: query
        name: page
        type: integer
      - default: 20
        description: Size
        in: query
        name: size
        type: integer
      - description: Category
        enum:
        - official
        - buffer
        in: query
        name: category
        type: string
      - description: Positions
        in: query
        name: positions
        type: string
      - description: Status
        enum:
        - active
        - inactive
        - pending
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListMembersResponse'
      summary: List members
      tags:
      - Member
    post:
      consumes:
      - application/json
      parameters:
      - description: Upsert Member body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpsertMemberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmptyResponse'
      summary: Upsert member
      tags:
      - Member
  /members/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmptyResponse'
      summary: Delete member
      tags:
      - Member
    get:
      consumes:
      - application/json
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetMemberResponse'
      summary: Get member
      tags:
      - Member
schemes:
- http
- https
swagger: "2.0"
