// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemberColumns holds the columns for the "member" table.
	MemberColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "level", Type: field.TypeInt},
		{Name: "positions", Type: field.TypeString},
		{Name: "kpi", Type: field.TypeInt},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"official", "buffer"}},
		{Name: "total_effort", Type: field.TypeFloat32},
		{Name: "start_date", Type: field.TypeTime, Nullable: true},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "pending"}},
	}
	// MemberTable holds the schema information for the "member" table.
	MemberTable = &schema.Table{
		Name:       "member",
		Columns:    MemberColumns,
		PrimaryKey: []*schema.Column{MemberColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemberTable,
	}
)

func init() {
	MemberTable.Annotation = &entsql.Annotation{
		Table: "member",
	}
}
